<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>IPPFileVersion</key>
	<string>Insensitive Pulse Program 0.9.24</string>
	<key>Name</key>
	<string>stegp1s</string>
	<key>PhaseCycles</key>
	<integer>4</integer>
	<key>PhaseCyclingArray</key>
	<array>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>270</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>180</real>
		<real>0.0</real>
		<real>180</real>
		<real>180</real>
	</array>
	<key>PulseSequence</key>
	<array>
		<data>
		AAAAAAAAtEIAAAAAAwAAAAAAAQABAABHAACAPgAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AgAAAAAAgD8AAPpGAAAAQAAAAAD/fwBHYQs2OwAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AAAAAAAAtEIAAAAAAwAAAAAAAQABAABHAACAPgAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AgAAAAAAgD8AUKvFAAAAsAAAAAD/fwBHYQs2OwAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AQAAAAAAgD8AAAAAAAAAQAAAAAABAABHYQs2OwAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AAAAAAAAtEIAADRDAwAAAAAAAQABAABHAACAPgAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AgAAAAAAgD8AAPpGAAAAIAAAAAD/fwBHYQs2OwAAgD8AAAAAAAAAAA==
		</data>
		<data>
		AwAAAAAAAEAAAAAAAAAAQAAAAQABAABHYQu2OwAAgD8AAAAAAAAAAA==
		</data>
	</array>
	<key>PurePhaseDetectionMethod</key>
	<integer>0</integer>
	<key>VariableEvolutionTime</key>
	<integer>5</integer>
</dict>
</plist>
