<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>IPPFileVersion</key>
	<string>Insensitive Pulse Program 0.9.7</string>
	<key>Name</key>
	<string>mlevph</string>
	<key>PhaseCycles</key>
	<integer>2</integer>
	<key>PhaseCyclingArray</key>
	<array>
		<real>0.0</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>180</real>
		<real>180</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>180</real>
		<real>270</real>
		<real>180</real>
		<real>0.0</real>
		<real>90</real>
		<real>0.0</real>
		<real>0.0</real>
		<real>0.0</real>
	</array>
	<key>PulseSequence</key>
	<array>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAAAAgD8AAAAAAAAAIAAAAAAAQAAA
		</data>
		<data>
		AAAAAAAAEEEAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAkAAAAAABAAD/
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAD/
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAUAAAAABvYgAA
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAIAAAAAAAQAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAQAAAAAAAAABAABg
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAoAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAsAAAAAAAAACA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAQAAAAAAwNQAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAQAAAAAABAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAEAAAAAABAABg
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAA8AAAAAAwNAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAA/
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAQAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAADw
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAQAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAAAAAAAAgIAAA
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAYAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAsAAAAAAAAAD/
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAD/
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAkAAAAAAAAAD/
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAkAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAQAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAIAAAAAABAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAA0AAAAAABAAAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAA8AAAAAAwOQAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAgAAAAAD/fwAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAsAAAAAABAABg
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAQAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAsAAAAAAAAAD/
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAD/
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAA8AAAAAAAAABg
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAADQ
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAIAAAAABNbwAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAwAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAgAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAA/
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAA8AAAAAAAAABg
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAEAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAIAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAkAAAAAAzNgBA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAAABA
		</data>
		<data>
		AAAAAAAANEMAAIdDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAIdDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAADRDBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AADRDAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAA4AAAAAD/fwBg
		</data>
		<data>
		AAAAAAAANEMAALRCBwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AALRCAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAtEIAAAAABwAAAAAAAQABAABg
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAsAAAAAAAAAAA
		</data>
		<data>
		AAAAAAAAcEIAAAAABwAAAAAAAQABAAAA
		</data>
		<data>
		AQAAAM3MzD0AAAAAAAAAwAAAAAABAAAA
		</data>
		<data>
		AAAAAAAAEEEAAAAABwAAAAAAAQABAABg
		</data>
		<data>
		AwAAAAAAALAAAAAAAAAAAAAAAQD/fwAA
		</data>
	</array>
	<key>PurePhaseDetectionMethod</key>
	<integer>1</integer>
	<key>VariableEvolutionTime</key>
	<integer>2</integer>
</dict>
</plist>
